package app.itgungnir.kwa.common

// 路由表
const val SplashActivity = "splash"
const val MainActivity = "main"
const val SearchResultActivity = "searchResult"
const val WebActivity = "web"
const val HierarchyActivity = "hierarchy"
const val LoginActivity = "login"
const val RegisterActivity = "register"
const val SettingActivity = "setting"
const val ScheduleActivity = "schedule"
const val ScheduleDoneActivity = "scheduleDone"

// HTTP
const val APP_VERSION = "V1.0.0"
const val HTTP_BASE_URL = "https://www.wanandroid.com"
const val HTTP_TIME_OUT = 5L
const val HTTP_LOG_TAG = "kotlin-wan-android"

// 图标
const val ICON_BACK = "\ue720"
const val ICON_HOME_NORMAL = "\ue703"
const val ICON_HOME_SELECT = "\ue702"
const val ICON_TREE_NORMAL = "\ue6ef"
const val ICON_TREE_SELECT = "\ue6ee"
const val ICON_WEIXIN_NORMAL = "\ue82c"
const val ICON_WEIXIN_SELECT = "\ue608"
const val ICON_PROJECT_NORMAL = "\ue6ec"
const val ICON_PROJECT_SELECT = "\ue6eb"
const val ICON_MINE_NORMAL = "\ue716"
const val ICON_MINE_SELECT = "\ue715"
const val ICON_AUTHOR = "\uE830"
const val ICON_UNCOLLECT = "\uE708"
const val ICON_COLLECT = "\uE707"
const val ICON_SHARE = "\ue729"
const val ICON_SEARCH = "\ue833"
const val ICON_TOOLS = "\ue834"
const val ICON_NAVIGATION = "\ue744"
const val ICON_ADD = "\ue6df"
const val ICON_SCHEDULE = "\ue6de"
const val ICON_SCHEDULE_DONE = "\ue732"
const val ICON_SETTING = "\ue728"
const val ICON_ARROW_UP = "\ue749"
const val ICON_ARROW_DOWN = "\ue74a"
const val ICON_FINISH = "\ue721"
const val ICON_AUTO_CACHE = "\ue791"
const val ICON_NO_IMAGE = "\ue63d"
const val ICON_DARK_MODE = "\ue633"
const val ICON_CLEAR_CACHE = "\ue6aa"
const val ICON_FEEDBACK = "\ue6f5"
const val ICON_ABOUT_US = "\ue601"

// 颜色
const val COLOR_PURE = "#FFFFFFFF"
const val COLOR_ACCENT = "#FFFF8F00"
const val COLOR_DIVIDER = "#FFC2C2C2"
const val COLOR_TEXT1 = "#FF373737"
const val COLOR_BACKGROUND = "#FFF5F5F5"
const val COLOR_ICON_NORMAL = "#FFC2C2C2"
const val COLOR_ICON_SELECT = "#FF707070"
const val COLOR_BG_WORK = "#FFB4004E"
const val COLOR_BG_LEARN = "#FF087F23"
const val COLOR_BG_LIFE = "#FF007AC1"
const val COLOR_PRIORITY_IMPORTANT = "#FFFF5722"
const val COLOR_PRIORITY_NORMAL = "#FF29B6F6"